Add overall output limit.
braincore/pid-rs pull request #6
Opened 2020-11-24 14:32 UTC by elionne

Because the PR #4 seems dead I created a new.

By the way, I defined a new function `magnitude_limit()`.

2020-11-27 04:49 UTC, braincore requested changes
Thanks for the diff!

Can you change the git commit msg to "Add control output limit."

2020-11-27 04:49 UTC, braincore commented on src/lib.rs
> +    fn magnitude_limit(limit: T, value: T) -> T {
Two things:

1. Let's call this `apply_limit()`.
2. Move this out of the `Pid` impl block since it's a pure function and doesn't need to be a part of `Pid`.

2020-11-27 04:49 UTC, braincore commented on src/lib.rs
> +    pub fn new(kp: T, ki: T, kd: T, p_limit: T, i_limit: T, d_limit: T, out_limit: T, setpoint: T) -> Self {
`out_limit` -> `output_limit` for consistency.

2020-11-27 04:49 UTC, braincore commented on README.md
> +* Overall output limit.
Three-term control output limit.

Also, can you remove the TODO item in the README about adding the three-term output limit?

2020-11-27 04:50 UTC, braincore commented
Just wondering, what are you applying this crate to? Do you have an active project?

2020-11-27 10:38 UTC, elionne commented
I'm developing my own MPPT Solar charger. I need a PID to control the PWM of a [Buck converter](https://en.wikipedia.org/wiki/Buck_converter) in order to have a stable output voltage.

I'm using the [Logan Nano board](https://www.seeedstudio.com/Sipeed-Longan-Nano-RISC-V-GD32VF103CBT6-Development-Board-p-4205.html) with the RISC-V [gd32vf103 chip](https://www.gigadevice.com/microcontroller/gd32vf103cbt6/), an equivalent of stm32f1.

It is the very beginning of the project. I'm co-developing it with a friend. The project is not visible yet (mostly because I'm shy). I do that on my own time.

Thank you for sharing your work  :+1: !

2020-11-29 01:52 UTC, braincore commented
Thanks for the changes and super cool application!

For future note, be sure to run `cargo fmt` (the new() function needs to wrap with the new arg) before committing (really, an automated test should check for it). I'll just do that as a separate commit.

2020-11-29 01:53 UTC, merged

2020-11-29 02:01 UTC, braincore commented
Published in v2.2.0.

2020-11-30 01:43 UTC, braincore commented
Per #7, the PR is actually in v3.0.0.