API reimplementation
braincore/pid-rs pull request #9
Opened 2021-05-19 11:20 UTC by Owez

Closes #8 

The current todo list is included within files, the current main checklist is:

- [ ] Speed testing
- [ ] General testing
- [ ] Finishing calculations
- [ ] Redoing examples for README.md
- [ ] Documentation

2021-05-19 18:40 UTC, braincore commented
Generally, the `PidSegment` abstraction isn't necessary for the (modest) complexity of the pid. There might be some performance implications as well (you do point out speed testing) which may impact those running this on no_std microcontroller environments.

My suggestion is to start with the existing code and simply add the p(), i(), d() functions that mutate kp, ki, kd.

2021-05-19 19:21 UTC, Owez commented
The equation listed on the current `master` readme is:

![PID independent form](
https://latex.codecogs.com/gif.latex?C(t)&space;=&space;&space;K_p&space;\cdot&space;e(t)&space;&plus;&space;K_i&space;\cdot&space;\int{e(t)dt}&space;-&space;K_d&space;\cdot&space;\frac{dP(t)}{dt})

Which includes a `-` instead of `+`; I assume this is a mistake?

2021-05-19 22:44 UTC, braincore commented
It's negative intentionally. We're using the change in process variable rather than change in error in this Pid, which has the desirably property of mitigating "derivative kick." I'll try to find you my original source that explained these optimizations clearly, but here's a quick source I found that does the job:

- https://controlguru.com/pid-control-and-derivative-on-measurement/ (section: Derivative on PV Used in Practice)

2021-05-20 11:52 UTC, Owez commented
Ahh alright thanks, I feel I looked at the code and saw `p + self.integral_term + d` and got confused

2021-05-21 05:55 UTC, braincore commented
Can you make this diff the bare minimum to change what's been discussed? You can follow up with other commits later to tweak the docs, etc... (happy to give you push access)

2021-05-21 14:34 UTC, Owez commented
:+1: Done with edbd3f2

2021-05-21 17:17 UTC, braincore requested changes
You should re-add the changes to the README related to this diff, i.e. the example section changes.

2021-05-21 17:17 UTC, braincore commented on src/lib.rs
>          self.integral_term = T::zero();
Using `i()` should not reset the integral term. For example, with a quadcopter, a significant amount of i-term builds up. Losing that i-term on a change in i() will result in potentially sluggish performance or even a crash. A lot of the i-term for flying is built up when taking off and is necessary for flight. Though it does make me wonder if there's a better way...

In short, there should continue to be a separate function `reset_integral_term()`.

2021-05-21 17:17 UTC, braincore commented on src/lib.rs
> +    pub fn new(limit: impl Into<T>) -> Self {
I think you suggested earlier to include the setpoint in the constructor. I was thinking the same as well. The pair `(setpoint, limit)` does not quite parallel the `(term, limit)` of the other functions though.

2021-05-21 17:17 UTC, braincore commented on src/lib.rs
> -    /// Given a new measurement, calculates the next control output.
The below changes to `next_control_output()` are superficial and don't need to be part of this diff. Sorry to be a stickler!

2021-05-21 18:53 UTC, braincore commented
In preparation for rebase, please squash everything down to one commit.

2021-05-22 01:17 UTC, Owez commented on src/lib.rs
> +    pub fn new(limit: impl Into<T>) -> Self {
Yeah I agree, I feel like this may be alright as the only real api conflict as the output limit may be more static then the other limits as its the final filter just used to cap values for more direct use. Do you think a change to something like `.cfg(SETPOINT, OUTPUT_LIMIT)` is warranted? I'm fine to implement it (would also mean that `::new()` can be replaced by a `::default()` impl).

2021-05-22 01:18 UTC, Owez commented on src/lib.rs
> -    /// Given a new measurement, calculates the next control output.
No problem, my bad for not changing the values upstream

2021-05-23 06:57 UTC, braincore commented on src/lib.rs
> +    pub fn new(limit: impl Into<T>) -> Self {
The drawback of `cfg()` is that, outside of initialization, `(setpoint, limit)` aren't likely to be modified together. I'm also inclined to retrace what I said earlier about `setpoint` defaulting to 0. It's better to be explicitly set by the user from the get-go, which makes `default()` not viable.

So, I'm good with `new::(setpoint, limit)`. You?

2021-05-23 06:58 UTC, braincore commented
Just that final comment. It's close!

2021-05-23 07:01 UTC, braincore commented
In addition to squashing the commits, make sure to give a condensed commit message. Something like "New API for configuring Pid" for the headline. For the body of the message, you can add the rationale for doing so: improved clarity of specification, make pid more approachable, improve developer experience, ...

2021-05-25 23:27 UTC, Owez commented
Apologies for the gap, final week and a half of school! Will add changes and push now

2021-05-25 23:45 UTC, Owez commented on src/lib.rs
> +    pub fn new(limit: impl Into<T>) -> Self {
Yep, added

2021-07-07 00:43 UTC, Owez commented
(Bump)

2022-01-30 00:38 UTC, quietlychris commented
@braincore Just wanted to check if this API change was still being considered! I was hoping to add a PID controller to a simulation I'm writing, and am definitely still interested in using this library.

2022-12-25 16:02 UTC, Owez commented
Bump @braincore

2022-12-25 20:13 UTC, ahepp commented on src/lib.rs
> +    /// Ideal setpoint to strive for
Could we fix this in a different patch? It seems to be causing a lot of diff noise

2022-12-25 22:49 UTC, braincore commented on README.md
> +    let mut pid = Pid::new(OUTPUT_LIMIT)
Mismatch with the new typedef: `new(setpoint, limit)`

Also, can you bring the README back into the same style as what was there before?
- The README example should be something that can be copy+pasted into a file and successfully run.
- Rather than use undefined variables, it should use real numbers and walk the user through it with comments.

2022-12-26 19:52 UTC, Owez commented on src/lib.rs
> +    /// Ideal setpoint to strive for
I've removed all the spacing when I was documenting a few mins ago, old stylistic choice I used to like

2022-12-26 19:53 UTC, Owez commented on README.md
> +    let mut pid = Pid::new(OUTPUT_LIMIT)
The existing README example was a bit long, I'll make it more concise and add some comments. I agree that the values should be real, fixing that and that old setpoint method now.

2022-12-26 20:40 UTC, braincore commented
Great! Thanks a ton for this work and apologies again that it took so long. I squashed and committed your branch outside of the PR flow (rebase workflow) so I'll close this PR manually.

2022-12-26 20:40 UTC, closed without merging